### ISSUE TITLE
Annotation viewer issues

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/derrida-django#208] opened 2018-04-25 16:46 UTC
- [ ] screen reader navigation aids to help users find annotations buttons (and aria description)?
- [ ] make zone divs `<button>` (`role="button"` seems not to help with tab finding in all browsers and button is best practice anyway. See here on [MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_button_role))

**Comment by rlskoeser** [comment] 2018-05-02 20:01
Duplicate of #204

**Closed by rlskoeser** 2018-05-02 20:01 UTC
Labels: accessibility, duplicate
