### ISSUE TITLE
interventions: associate with IIIF canvases

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/derrida-django#27] opened 2017-04-24 14:01 UTC
As an intervention data editor, I want to associate individual canvases or canvas pages with the book record in the system so that I can connect the digitized version with the information about the book, and so that I can document interventions on the pages.

**Comment by rlskoeser** [comment] 2017-07-13 19:46
I think we determined this was a duplicate of #7.

**Closed by rlskoeser** 2017-07-13 19:46 UTC
Labels: duplicate
